package io.spill.idiom

import io.spill.ast._
import io.spill.NamingStrategy
import io.spill.context.Capabilities

trait Idiom extends Capabilities {

  def emptySetContainsToken(field: Token): Token = StringToken("FALSE")

  def defaultAutoGeneratedToken(field: Token): Token =
    StringToken("DEFAULT VALUES")

  def liftingPlaceholder(index: Int): String

  def translate(ast: Ast)(implicit naming: NamingStrategy): (Ast, Statement)

  def format(queryString: String): String = queryString

  def prepareForProbing(string: String): String
}
